server:
  port: 8085

spring:
  thymeleaf:
    cache: false
  datasource:
    url: ${DATABASE_URL}
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: jeonyu2913@gmail.com
    password: kyaiitktmdqcxsst
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
logging:
  level:
    org.springframework.web: debug

aes:
  secret-key: ${AES_SECRET_KEY}


aws:
  s3:
    bucket: jeon-test-bucket
    region: ap-northeast-2
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}


jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 7200000